Found_Eng=float(input("Input Foundation English score : "))
Gen_Buss=float(input("Input General Business score : "))
Intro_Com=float(input("Input Introduction to Computer Systems score : "))
Com_program=float(input("Input Computer Programming score : "))
print("---Your Score---")
print("Foundation English : ",Found_Eng)
print("General Business : ",Gen_Buss)
print("Introduction to Computer Systems : ",Intro_Com)
print("Computer Programming : ",Com_program)
